### ISSUE TITLE
Update CI to use Solutions & Portable DebugTypes

### ISSUE THREAD

**Issue by carusology** [invio/Invio.Extensions.DependencyInjection#14]
**Background**
As part of our migration to v1.0.4 of the .NET SDK, I [set the `DebugType` to `full`](https://github.com/invio/Invio.Extensions.DependencyInjection/commit/df2b1cdb2caa47e663be7edbe1a80476cda60b98#diff-d28243c1846785f0e06aacf27f98e184R8) and updated the CI scripts to explicitly reference XML-based `*.csproj` files due to the removal of `global.json` and `project.json`. The `DebugType` really should be `portable` for .NET Core when we pack the code (though it needs to be `full` for when we run opencover on it), and we should add a `*.sln` to manage our `*.csproj` files.

**Task**
* [x] Update the repository to have a `Invio.Extensions.DependencyInjection.sln` solution at the root of the repository that references the source and test projects.
* [x] Update `Invio.Extensions.DependencyInjection.csproj` such that `<IsPackable>false</IsPackable>` is specified.
* [x] Restore `set-debug-type.ps1`, but with it updating the `DebugType` via the XML-based `Invio.Extensions.DependencyInjection.csproj` instead of JSON-based `project.json`.
